WebAsset/Models/Asset.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace WebAsset.Models
{
    public class Asset
    {
        [Key]
        public int AssetId { get; set; }

        [Required(ErrorMessage = "Fill the Name space")]
        [Display(Name = "Asset Name:")]
        [StringLength(30, ErrorMessage = "Name not to be exceed")]
        public string AssetName { get; set; }

        public string AssetType { get; set; }

        [Required(ErrorMessage = "Enter the Serial Number")]
        public int AssetSku { get; set; }

        [Required(ErrorMessage = "Enter the right price")]
        //[Range(1,1000000)]
        public int Price { get; set; }

        [Required(ErrorMessage = "Enter the number of assets")]
        //[Range(1, 10000)]
        public int CountAsset { get; set; }

        public string Description { get; set; }

        [Required(ErrorMessage = "Enter the vendor name")]
        public string Vendor { get; set; }
        //[DataType(DataType.Date)]
        public DateTime? CreatedOn { get; set; }

        //[DataType(DataType.Date)]
        public DateTime? UpdatedOn { get; set; }
    }

}

WebAsset/Controllers/AssetController.cs
using WebAsset.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebAsset.Controllers
{
    public class AssetController : Controller
    {
        DataAccess Da = new DataAccess();
        private AssetDbContext db = new AssetDbContext();

        //public ActionResult Frontui()
        //{
        //    ViewBag.Title = "Asset Ninja";

        //    return View();
        //}
        public ActionResult Index()
        {
            ViewBag.Title = "Asset Ninja";

            return View();
        }

        public ActionResult GetAsset(string SortOrder)
        {
            ViewBag.AssetName = string.IsNullOrEmpty(SortOrder) ? "AssetName_desc" : "";
            ViewBag.AssetType = SortOrder == "AssetType" ? "AssetType_desc" : "AssetType";


            var emp = from s in db.Assets
                      select s;

            switch (SortOrder)
            {
                case "AssetName_desc":
                    emp = emp.OrderByDescending(s => s.AssetName);
                    break;
                case "AssetType":
                    emp = emp.OrderBy(s => s.AssetType);
                    break;
                case "AssetType_desc":
                    emp = emp.OrderByDescending(s => s.AssetType);
                    break;
                default:
                    emp = emp.OrderBy(s => s.AssetName);
                    break;
            }


            List<Asset> Ast = Da.GetAllAssets();
            return View(emp.ToList());


        }

        [HttpGet]
        public ActionResult AddAsset()
        {
          
                Asset Ast = new Asset();
                return View(Ast);
        

        }


        [HttpPost]
        public ActionResult AddAsset(Asset Ast)
        {
            if (ModelState.IsValid)
            {

                int iresult = Da.AddAsset(Ast);
                TempData["SuccessMessage"] = "Added Successfully";
                return RedirectToAction("Index");
            }
            return View();


        }

        public ActionResult EditAssets(string SortOrder)
        {
            ViewBag.AssetName = string.IsNullOrEmpty(SortOrder) ? "AssetName_desc" : "";
            ViewBag.AssetSku = SortOrder == "AssetSku" ? "AssetSku_desc" : "AssetSku";


            var emp = from s in db.Assets
                      select s;

            switch (SortOrder)
            {
                case "AssetName_desc":
                    emp = emp.OrderByDescending(s => s.AssetName);
                    break;
                case "AssetSku":
                    emp = emp.OrderBy(s => s.AssetSku);
                    break;
                case "AssetSku_desc":
                    emp = emp.OrderByDescending(s => s.AssetSku);
                    break;
                default:
                    emp = emp.OrderBy(s => s.AssetName);
                    break;
            }
            List<Asset> Ast = Da.GetAllAssets();
            return View(emp.ToList());

        }


        [HttpGet]
        public ActionResult EditAsset(int id)
        {
            Asset iresult = Da.ChangeStudent(id);
            return View(iresult);

        }

        [HttpPost]
        public ActionResult EditAsset(Asset Ast)
        {
            if (ModelState.IsValid)
            {
                Da.UpdateAsset(Ast);
                TempData["SuccessMessage"] = "Edited Successfully";
                return RedirectToAction("Index");
            }
            return View();
        }

        

        [HttpGet]
        public ActionResult DeleteAsset(int id)
        {
            Asset iresult = Da.ChangeDeleteAsset(id);
            return View(iresult);

        }

        [HttpPost, ActionName("DeleteAsset")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteAssetss(int id)
        {
            Da.DeleteAssets(id);
            TempData["SuccessMessage"] = "Deleted Successfully";
            return RedirectToAction("Index");
        }

        public ActionResult DeleteAssets(string SortOrder)
        {

            ViewBag.AssetName = string.IsNullOrEmpty(SortOrder) ? "AssetName_desc" : "";
            ViewBag.AssetType = SortOrder == "AssetType" ? "AssetType_desc" : "AssetType";


            var emp = from s in db.Assets
                      select s;

            switch (SortOrder)
            {
                case "AssetName_desc":
                    emp = emp.OrderByDescending(s => s.AssetName);
                    break;
                case "AssetType":
                    emp = emp.OrderBy(s => s.AssetType);
                    break;
                case "AssetType_desc":
                    emp = emp.OrderByDescending(s => s.AssetType);
                    break;
                default:
                    emp = emp.OrderBy(s => s.AssetName);
                    break;
            }
            List<Asset> Ast = Da.GetAllAssets();
            return View(emp.ToList());

        }

        //[HttpGet]
        //public ActionResult DeleteAsset(int id)
        //{
        //    Asset A1 = Da.ChangeStudent(id);
        //    return View(A1);

        //}


        //[HttpPost]
        //public ActionResult DeleteAsset(Asset Ast)
        //{
        //    Da.DeleteAssets(Ast);
        //    TempData["SuccessMessage"] = "Saved Successfully";
        //    return RedirectToAction("GetAsset");
        //}

        //public ActionResult DeleteAssets()
        //{
        //    List<Asset> Ast = Da.GetAllAssets();
        //    return View(Ast);

        //}







    }

}

WebAsset/Views/Asset/AddAsset.cshtml
@model WebAsset.Models.Asset

@{
    ViewBag.Title = "AddAsset";
}

<head>
    <h2 class="mintitle" style="font-family: 'Times New Roman'; font-weight: 1000; font-size: 40pxl;"><i class="fa-solid fa-plus-large"></i>Add Asset</h2>
    @Styles.Render("~/css/AddAsset.css")
  
</head>

<body>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        <form>
            <link rel="preconnect" href="https://fonts.gstatic.com">
            <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400;500&display=swap" rel="stylesheet">
            <main>
                <section class="glass">
                    <div class="dashboard">
                        <div class="links">
                            <div class="link">
                                <h3>Asset Name</h3>

                            </div>
                            <div class="link">
                                <h3>Asset Type</h3>

                            </div>
                            <div class="link">
                                <h3>Asset Sku</h3>

                            </div>
                            <div class="link">
                                <h3>Price</h3>
                            </div>

                            <div class="link">
                                <h3>Count Asset</h3>
                            </div>
                            <div class="link">
                                <h3>Description</h3>
                            </div><br />

                            <div class="link">
                                <h3>Vendor</h3>
                            </div>
                            @*<div class="link">
                        <h3>Created On</h3>
                    </div>*@

                        </div>

                    </div>
                    <div class="dashboard1">
                        <div class="link">
                            <h2 class="input">
                                @Html.EditorFor(model => model.AssetName, new { htmlAttributes = new { @class = "form-control" } })
                            </h2>
                            <span style="font-family:'Times New Roman';font-size:small;color:brown;"> @Html.ValidationMessageFor(model => model.AssetName, "", new { @class = "validation_error" })</span>

                        </div>
                        <div class="link">
                            <h2 class="input">
                                @*@Html.EditorFor(model => model.AssetType, new { htmlAttributes = new { @class = "form-control" } })*@
                                @Html.DropDownList("AssetType", new List<SelectListItem>
                           {
                               new SelectListItem{Text="Electronics"},
                                new SelectListItem{Text="Software"},
                                 new SelectListItem{Text="Machinary"},
                                  new SelectListItem{Text="IT Asset"},
                                   new SelectListItem{Text="Security"},
                                    new SelectListItem{Text="Furnitures"},
                           new SelectListItem{Text="Others"}}, "Select Asset Type", htmlAttributes: new { @class = "btn btn-default" }
                               )
                            </h2>
                            <p style="font-family: 'Times New Roman'; font-size: small;"> @Html.ValidationMessageFor(model => model.AssetType, "", new { @class = "text-danger" })</p>

                        </div>
                        <div class="link">
                            <h2 class="input">
                                @Html.EditorFor(model => model.AssetSku, new { htmlAttributes = new { @class = "form-control" } })
                            </h2>
                            <p style="font-family: 'Times New Roman'; font-size: small;"> @Html.ValidationMessageFor(model => model.AssetSku, "", new { @class = "text-danger" })</p>

                        </div>
                        <div class="link">
                            <h2 class="input">
                                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                            </h2>
                            <p style="font-family: 'Times New Roman'; font-size: small;">  @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })</p>

                        </div>
                        <div class="link">
                            <h2 class="input">
                                @Html.EditorFor(model => model.CountAsset, new { htmlAttributes = new { @class = "form-control" } })
                            </h2>
                            <p style="font-family: 'Times New Roman'; font-size: small;"> @Html.ValidationMessageFor(model => model.CountAsset, "", new { @class = "text-danger" })</p>

                        </div>
                        <div class="link">
                            <h2 class="input"style="color:black;font-family:Georgia, 'Times New Roman', Times, serif;font-size:medium">
                                @Html.TextAreaFor(model => model.Description, new { htmlAttributes = new { @class = "fo" } })
                            </h2>
                            <p style="font-family: 'Times New Roman'; font-size: small;"> @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })</p>
                        </div>
                        <div class="link">
                            <h2 class="input">
                                @Html.EditorFor(model => model.Vendor, new { htmlAttributes = new { @class = "form-control" } })
                            </h2>
                            <p style="font-family: 'Times New Roman'; font-size: small;"> @Html.ValidationMessageFor(model => model.Vendor, "", new { @class = "text-danger" })</p>

                        </div>
                        @*<div class="link">
                    <h2 class="input">
                        @Html.EditorFor(model => model.CreatedOn, new { htmlAttributes = new { @class = "form-control" } })
                    </h2>
                    <p style="font-family: 'Times New Roman'; font-size: small;"> @Html.ValidationMessageFor(model => model.CreatedOn, "", new { @class = "text-danger" })</p>
                </div>*@

                    </div>



                </section>
                <div class="btn_group">
                    @*<button class="btn btn-default" title="Menu"><a href="@Url.Action("Index", "Asset")"><i class="fa-solid fa-backward"></i></a></button>
            <button class="btn btn-default" title="View"><a href="@Url.Action("GetAsset", "Asset")"><i class="fa-sharp fa-solid fa-eye"></i></a></button>*@
                    @*<button class="btn btn-default" title="Menu">@Html.ActionLink("Home", "Index")</button>*@
                    @*<button class="btn btn-default"><a href="@Url.Action("Index", "Asset")"><i class="fa-sharp fa-solid fa-eye"></i></a></button>*@
                    <button class="btn btn-primary btn-lg" title="Save">Save</button>
                </div>
            </main>
        </form>}

</body>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WebAsset/Views/Asset/DeleteAssets.cshtml
@model IEnumerable<WebAsset.Models.Asset>

@{
    ViewBag.Title = "DeleteAssets";
}

<head>
    @Styles.Render("~/css/DeleteAssets.css")
    <div>

        <p class="mintitle">Delete Asset</p>
    </div>


</head>

<body>

    @foreach (var item in Model)
    {
        <div class="cards">
            <div class="card card-1">
                <th class="card__title">SKU: @Html.DisplayFor(modelItem => item.AssetSku)</th><br />
                <th class="card__title">Asset Name: @Html.DisplayFor(modelItem => item.AssetName)</th><br />
                <th class="card__title">Asset Type: @Html.DisplayFor(modelItem => item.AssetType)</th><br />
                <th class="card__title">Price:  @Html.DisplayFor(modelItem => item.Price)</th><br />
                <th class="card__title">Count: @Html.DisplayFor(modelItem => item.CountAsset)</th><br />
                <th class="card__title">Description:  @Html.DisplayFor(modelItem => item.Description)</th><br />
                <th class="card__title">Vendor:  @Html.DisplayFor(modelItem => item.Vendor)</th><br />
                @*<th class="card__title">Created On:  @Html.DisplayFor(modelItem => item.CreatedOn)</th><br />*@

                <div class="btn_group">
                    <button class="btn btn-default"><a href="@Url.Action("DeleteAsset", "Asset", new { id = item.AssetId })">@*<i class="fa-solid fa-trash"></i>*@Delete</a></button>
                    @*<button class="btn btn-default"><a href="@Url.Action("Index", "Asset")"><i class="fa-sharp fa-solid fa-eye"></i></a></button>*@
                </div>

            </div>

        </div>

    }



</body>

WebAsset/Views/Asset/EditAsset.cshtml
@model WebAsset.Models.Asset

@{
    ViewBag.Title = "EditAsset";
}

<head>
    <h2 class="mintitle">Edit Asset</h2>
    @Styles.Render("~/css/EditAsset.css")
</head>

<body style=" background-color: linear-gradient(to right bottom,rgba(41,128,185, 0.7), rgba(44,62,80,0.3));">
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
    <form>

        <link rel="preconnect" href="https://fonts.gstatic.com">
        <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400;500&display=swap" rel="stylesheet">
        <main>
            <section class="glass">
                <div class="dashboard">
                    <div class="links">
                        <div class="link">
                            <h3>Asset Name</h3>

                        </div>
                        <div class="link">
                            <h3>Asset Type</h3>

                        </div>
                        <div class="link">
                            <h3>Asset Sku</h3>

                        </div>
                        <div class="link">
                            <h3>Price</h3>
                        </div>

                        <div class="link">
                            <h3>Count Asset</h3>
                        </div>
                        <div class="link">
                            <h3>Description</h3>
                        </div>

                        <div class="link">
                            <h3>Vendor</h3>
                        </div>
                        @*<div class="link">
                            <h3>Created On</h3>
                        </div>*@

                    </div>

                </div>
                <div class="dashboard1">
                    <div class="link">
                        <h2 class="input">
                            @Html.EditorFor(model => model.AssetName, new { htmlAttributes = new { @class = "form-control" } })
                        </h2>
                        <span style="font-family:'Times New Roman';font-size:small;color:brown;"> @Html.ValidationMessageFor(model => model.AssetName, "", new { @class = "validation_error" })</span>

                    </div>
                    <div class="link">
                        <h2 class="input">
                            @*@Html.EditorFor(model => model.AssetType, new { htmlAttributes = new { @class = "form-control" } })@*@
                            @Html.DropDownList("AssetType", new List<SelectListItem>
                       {
                           new SelectListItem{Text="Electronics"},
                            new SelectListItem{Text="Software"},
                             new SelectListItem{Text="Machinary"},
                              new SelectListItem{Text="IT Asset"},
                               new SelectListItem{Text="Security"},
                                new SelectListItem{Text="Furnitures"},
                       new SelectListItem{Text="Others"}}, "Select Asset Type", htmlAttributes: new { @class = "btn btn-default" }
)
                        </h2>
                        <p style="font-family: 'Times New Roman'; font-size: small;"> @Html.ValidationMessageFor(model => model.AssetType, "", new { @class = "text-danger" })</p>

                    </div>
                    <div class="link">
                        <h2 class="input">
                            @Html.EditorFor(model => model.AssetSku, new { htmlAttributes = new { @class = "form-control" } })
                        </h2>
                        <p style="font-family: 'Times New Roman'; font-size: small;"> @Html.ValidationMessageFor(model => model.AssetSku, "", new { @class = "text-danger" })</p>

                    </div>
                    <div class="link">
                        <h2 class="input">
                            @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                        </h2>
                        <p style="font-family: 'Times New Roman'; font-size: small;">  @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })</p>

                    </div>
                    <div class="link">
                        <h2 class="input">
                            @Html.EditorFor(model => model.CountAsset, new { htmlAttributes = new { @class = "form-control" } })
                        </h2>
                        <p style="font-family: 'Times New Roman'; font-size: small;"> @Html.ValidationMessageFor(model => model.CountAsset, "", new { @class = "text-danger" })</p>

                    </div>
                    <div class="link">
                        <h2 class="input" style="color:black;font-family:Georgia, 'Times New Roman', Times, serif;font-size:medium">
                            @Html.TextAreaFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                        </h2>
                        <p style="font-family: 'Times New Roman'; font-size: small;"> @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })</p>
                    </div>
                    <div class="link">
                        <h2 class="input">
                            @Html.EditorFor(model => model.Vendor, new { htmlAttributes = new { @class = "form-control" } })
                        </h2>
                        <p style="font-family: 'Times New Roman'; font-size: small;"> @Html.ValidationMessageFor(model => model.Vendor, "", new { @class = "text-danger" })</p>

                    </div>
                    @*<div class="link">
                        <h2 class="input">
                            @Html.EditorFor(model => model.CreatedOn, new { htmlAttributes = new { @class = "form-control" } })
                        </h2>
                        <p style="font-family: 'Times New Roman'; font-size: small;"> @Html.ValidationMessageFor(model => model.CreatedOn, "", new { @class = "text-danger" })</p>
                    </div>*@

                </div>



                @*<p class="btn-group"> <input type="submit" value="Save" class="View" />
                    <button><input type="submit" value="Save" class="View" /></button>
                </p>*@

            </section>
        </main>

        <div class="btn_group">
           
            @*@<button class="btn btn-default" title="Menu">@Html.ActionLink("Home", "Index")</button>@
            @<button class="btn btn-default"><a href="@Url.Action("Index", "Asset")"><i class="fa-sharp fa-solid fa-eye"></i></a></button>@*@
            <button class="btn btn-default" title="Save">Save</button>

        </div>
    </form>
    }
</body>

<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery-3.4.1.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

}

WebAsset/Views/Asset/EditAssets.cshtml
@model IEnumerable<WebAsset.Models.Asset>

@{
    ViewBag.Title = "EditAssets";
}

<head>
    @Styles.Render("~/css/EditAssets.css")
    <div>

        <p class="mintitle">Edit Asset</p>
    </div>

</head>

<body>
    @using (Html.BeginForm("EditAssets", "Asset", FormMethod.Get))
    {
        <div class="col-sm-9 col-xs-12 text-right">
            <div class="btn_group">
                <button class="btn btn-default btn-lg" title="SortByAssetName"style="color:aliceblue;font-weight:600">
                    @Html.ActionLink("Asset Name", "EditAssets", new { SortOrder = ViewBag.AssetName })
                </button>
                <button class="btn btn-default btn-lg" title="SortByAssetSku"style="color:aliceblue;font-weight:600">
                    @Html.ActionLink("Asset SKU", "EditAssets", new { SortOrder = ViewBag.AssetSku })
                </button>
                <button class="btn btn-default btn-lg" title="Menu"style="color:aliceblue;font-weight:600">
                    @Html.ActionLink("Home", "Index")
                </button>
            </div>
        </div>

    }
    @foreach (var item in Model)
    {
        <div class="cards">
            <div class="card card-1">
                <th class="card__title">SKU: @Html.DisplayFor(modelItem => item.AssetSku)</th><br />
                <th class="card__title">Asset Name: @Html.DisplayFor(modelItem => item.AssetName)</th><br />
                <th class="card__title">Asset Type: @Html.DisplayFor(modelItem => item.AssetType)</th><br />
                                                                                                     
                <div class="btn_group">
                    <button class="btn btn-default"><a href="@Url.Action("EditAsset", "Asset", new { id = item.AssetId })">Edit</a></button>
                    @*<button class="btn btn-default"><a href="@Url.Action("GetAssetList", "Asset")"><i class="fa-sharp fa-solid fa-eye"></i></a></button>*@
                </div>
            </div>
        </div>

    }



</body>

WebAsset/Views/Asset/GetAsset.cshtml
@model IEnumerable<WebAsset.Models.Asset>

@{
    ViewBag.Title = "ViewAsset";
}

<head>
    @Styles.Render("~/css/GetAsset.css")
    <style>
        th {
            font-family: serif;
            font-weight: 900;
        }
    </style>
</head>

<body>
    @using (Html.BeginForm("GetAsset", "Asset", FormMethod.Get))
    {
        <div class="container">
            <div class="row">
                <div class="col-md-offset-1 col-md-10">
                    <div class="panel">
                        <div class="panel-heading">
                            <div class="row">
                                <div class="col col-sm-3 col-xs-12">
                                    <h4 class="title" style="font-family:'Times New Roman';font-weight:1000;font-size:40px">Asset <span>List</span></h4>
                                </div>
                                <div class="col-sm-9 col-xs-12 text-right">
                                    <div class="btn_group">
                                        <input type="text" class="form-control" placeholder="Search">

                                        <button class="btn btn-primary btn-lg" title="SortByAssetName"><i class="fa-solid fa-arrow-down-arrow-up"></i>@Html.ActionLink("SortName", "GetAsset", new { SortOrder = ViewBag.AssetName }, new { style = "color:white;font-weight:900;" })</button>
                                        <button class="btn btn-primary btn-lg" title="SortByAssetType"><i class="fa-solid fa-arrow-down-arrow-up"></i> @Html.ActionLink("SortType ", "GetAsset", new { SortOrder = ViewBag.AssetType }, new { style = "color:white;font-weight:900;" })</button>
                                        <button class="btn btn-primary btn-lg" title="Menu">@Html.ActionLink("Home", "Index", new { }, new { style = "color:white;font-weight:900;" })</button>
                                        @*<button class="btn btn-default"><a href="@Url.Action("Index", "Asset")"><i class="fa-sharp fa-solid fa-eye"></i></a></button>*@
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="panel-body table-responsive">
                            <table class="table">
                                <thead>
                                    <tr>

                                        <th style=" color: #ffffff; font-size: 20px; padding: 10px 12px; vertical-align: middle;">Asset Name</th>
                                        <th  style="color: #ffffff; font-size: 20px; padding: 10px 12px; vertical-align: middle; ">Asset Type</th>
                                        <th  style="color: #ffffff; font-size: 20px; padding: 10px 12px; vertical-align: middle; ">Asset SKU</th>
                                        <th  style="color: #ffffff; font-size: 20px; padding: 10px 12px; vertical-align: middle; ">Price</th>
                                        <th  style="color: #ffffff; font-size: 20px; padding: 10px 12px; vertical-align: middle; ">Count</th>
                                        <th  style="color: #ffffff; font-size: 20px; padding: 10px 12px; vertical-align: middle; ">Description</th>
                                        <th  style="color: #ffffff; font-size: 20px; padding: 10px 12px; vertical-align: middle; ">Vendor</th>
                                        <th  style="color: #ffffff; font-size: 20px; padding: 10px 12px; vertical-align: middle; ">Created On</th>
                                        <th  style="color: #ffffff; font-size: 20px; padding: 10px 12px; vertical-align: middle; ">Updated On</th>

                                    </tr>
                                </thead>


                                @foreach (var item in Model)
                                {

                            <tr>

                                <td> @Html.DisplayFor(modelItem => item.AssetName)</td>
                                <td>@Html.DisplayFor(modelItem => item.AssetType)</td>
                                <td>@Html.DisplayFor(modelItem => item.AssetSku)</td>
                                <td>@Html.DisplayFor(modelItem => item.Price)</td>
                                <td> @Html.DisplayFor(modelItem => item.CountAsset)</td>
                                <td> @Html.DisplayFor(modelItem => item.Description)</td>
                                <td>@Html.DisplayFor(modelItem => item.Vendor)</td>
                                <td>@Html.DisplayFor(modelItem => item.CreatedOn)</td>
                                <td>@Html.DisplayFor(modelItem => item.UpdatedOn)</td>
                            </tr>
                                    <br />

                                }

                            </table>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    }


</body>

WebAsset/Views/Asset/Index.cshtml
@model IEnumerable<WebAsset.Models.Asset>

@{
    ViewBag.Title = "Index";
}


<head>
    @Styles.Render("~/css/Index.css")
</head>

<body>
    <marquee direction="left" style="color:#ffffff; font-size: 30px;">Asset Management Application</marquee>
    <div class="hero2">
        <!--This feels like the wrong solution here :/ -->
        <fieldset class="hero2-text">
            <legend class="border-text">&nbsp; be impressed</legend>
            <h1>Asset Ninja</h1>
            <p>Now you can manage the organization assets easily and efficiently!!</p>
            @*<a href="#scroll2"><button>click me</button></a>*@
            <a href="@Url.Action("GetAsset", "Asset")" class="View"><button>View Asset</button></a>
            <a href="@Url.Action("AddAsset", "Asset")" class="View"><button>Add Asset</button></a><br /><br />
            <a href="@Url.Action("EditAssets", "Asset")" class="View"><button>Edit Asset</button></a>
            <a href="@Url.Action("DeleteAssets", "Asset")" class="View"><button>Delete Asset</button></a><br /><br />
        </fieldset>
    </div>


</body>


@section scripts
{
    <script>
        $(function () {
            var successMessage = '@TempData["SuccessMessage"]'
            if (successMessage != '')
                alertify
                    .alert('Asset Ninja',successMessage, function () {

                    });
            });

    </script>
}